spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    北京库
#    url: jdbc:mysql://bj-cdb-bb3z5kdj.sql.tencentcdb.com:63920/blog?characterEncoding=utf8&useSSL=true&useUnicode=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: jin321jin321
    url: jdbc:mysql://119.28.27.175:3306/blog?characterEncoding=utf8&useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 19970829hh
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/jsp/



